version: '3'

services:
  bot:
    build:
      context: bot-gateway
      dockerfile: Dockerfile
    container_name: bot
    links:
      - mongo
      - redis
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - scheduler
    networks:
      - tgbot

  scheduler:
    build:
      context: scheduler-service
      dockerfile: Dockerfile
    container_name: scheduler
    ports:
      - 8002:8002
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - tgbot

  mongo:
    image: mongo
    container_name: tgbotmongo
    ports:
      - 27018:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=tgbot_test
      - MONGO_INITDB_ROOT_USERNAME=testUser
      - MONGO_INITDB_ROOT_PASSWORD=testPass
    volumes:
      - ./.storage-data/mgdb:/data/db
    networks:
      - tgbot

  redis:
    image: redis:alpine
    container_name: tgbotredis
    ports:
      - '6380:6379'
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass testPass
    volumes:
      - ./.storage-data/rdb:/usr/local/etc/redis/redis.conf
    networks:
      - tgbot

  postgres:
    image: postgres:alpine
    container_name: tgbotpostgres
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPass
      - POSTGRES_DB=testDB
    restart: unless-stopped
    volumes:
      - ./.storage-data/pg:/var/lib/postgresql/data
    networks:
      - tgbot

networks:
  tgbot:
    driver: bridge
