version: '3'

services:
  mongotest:
    image: mongo
    container_name: mongotest
    ports:
      - 27019:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=tgbot_test
      - MONGO_INITDB_ROOT_USERNAME=testUser
      - MONGO_INITDB_ROOT_PASSWORD=testPass
    volumes:
      - ./.storage-test/mgdbtest:/data/db

  redistest:
    image: redis:alpine
    container_name: redistest
    ports:
      - 6381:6379
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass testPass
    volumes:
      - ./.storage-test/rdbtest:/usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:alpine
    container_name: postgrestest
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPass
      - POSTGRES_DB=testDB
    volumes:
      - ./.storage-test/pg:/var/lib/postgresql/data