version: '3'

services:
  bot:
    build:
      context: bot-gateway
      dockerfile: Dockerfile
    container_name: bot
    links:
      - mongo
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - tgbot

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=tgbot_test
      - MONGO_INITDB_ROOT_USERNAME=testUser
      - MONGO_INITDB_ROOT_PASSWORD=testPass
    volumes:
      - ./.storage-data/mgdb:/data/db
    networks:
      - tgbot

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6380:6379'
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass testPass
    volumes:
      - ./.storage-data/rdb:/usr/local/etc/redis/redis.conf
    networks:
      - tgbot

networks:
  tgbot:
    driver: bridge
