version: '3'

services:
  mongodb:
    image: mongo
    container_name: tg_mongodb
    ports:
      - 27020:27017
    env_file:
      - ./.env
    volumes:
      - ./_storage-data/mgdb:/data/db
  
  redis:
    image: redis:alpine
    container_name: tg_redis
    ports:
      - 6380:6379
    environment:
      - name=value
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass testPass
    volumes:
      - ./_storage-data/rdb:/usr/local/etc/redis/redis.conf